services:

  postgres:
    image: postgres:16
    container_name: novahr-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: novahr
      POSTGRES_USER: novahr
      POSTGRES_PASSWORD: novahr_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:

  postgres_data:

